from dataclasses import dataclass
from typing import Optional, Any
from decimal import Decimal

@dataclass
class InitialInputsData:
    mgmt_type: str
    proj_ctgry: str
    proj_type: str
    proj_years: int
    const_years: int
    ijikanri_unnei_years: int
    const_start_date: str
    kijun_kinri: str
    chisai_kinri: str
    chisai_sueoki_kikan: int
    chisai_shoukan_kikan: int
    lg_spread: str
    zei_modori: str
    zei_total: str
    riyou_ryoukin: str
    growth: str
    kitai_bukka: str
    shisetsu_seibi: str
    shisetsu_seibi_org: str
    shisetsu_seibi_org_LCC: str
    shisetsu_seibi_LCC: str
    ijikanri_unnei_1: str
    ijikanri_unnei_1_org: str
    ijikanri_unnei_1_org_LCC: str
    ijikanri_unnei_1_LCC: str
    ijikanri_unnei_2: str
    ijikanri_unnei_2_org: str
    ijikanri_unnei_2_org_LCC: str
    ijikanri_unnei_2_LCC: str
    ijikanri_unnei_3: str
    ijikanri_unnei_3_org: str
    ijikanri_unnei_3_org_LCC: str
    ijikanri_unnei_3_LCC: str
    yosantanka_hiritsu_shisetsu: str
    yosantanka_hiritsu_ijikanri_1: str
    yosantanka_hiritsu_ijikanri_2: str
    yosantanka_hiritsu_ijikanri_3: str
    rakusatsu_ritsu: str
    reduc_shisetsu: str
    reduc_ijikanri_1: str
    reduc_ijikanri_2: str
    reduc_ijikanri_3: str
    pre_kyoukouka: bool
    kisai_jutou: str
    kisai_koufu: str
    hojo_ritsu: str
    zeimae_rieki: str
    SPC_keihi: str
    SPC_fee: str
    SPC_shihon: str
    SPC_yobihi: str
    SPC_hiyou_atsukai: int
    houjinzei_ritsu: str
    houjinjuminzei_kintou: str
    hudousanshutokuzei_hyoujun: str
    hudousanshutokuzei_ritsu: str
    koteishisanzei_hyoujun: str
    koteishisanzei_ritsu: str
    tourokumenkyozei_hyoujun: str
    tourokumenkyozei_ritsu: str
    houjinjuminzei_ritsu_todouhuken: str
    houjinjuminzei_ritsu_shikuchoson: str

@dataclass
class UIInputsData:
    const_start_date_year: int
    const_start_date_month: int
    const_start_date_day: int
    chisai_shoukan_kikan: int
    shisetsu_seibi_ikkatsu_hiritsu: Decimal
    monitoring_costs_PSC: Decimal
    monitoring_costs_LCC: Decimal
    kisai_jutou: Decimal
    kisai_koufu: Decimal
    hojo_ritsu: Decimal
    SPC_keihi: Decimal
    SPC_fee: Decimal
    SPC_shihon: Decimal
    SPC_yobihi: Decimal
    advisory_fee: Decimal
    riyouryoukin_shunyu: Decimal
    kappu_kinri_spread: Decimal
    chisai_sueoki_kikan: int
    option_02: Decimal

@dataclass
class CalculatedFinancialData:
    advisory_fee: str
    chisai_kinri: str
    chisai_shoukan_kikan: int
    chisai_sueoki_years: int
    const_start_date_year: int
    const_start_date_month: int
    const_start_date_day: int
    const_start_date: str
    const_years: int
    discount_rate: str
    first_end_fy: str
    fudousanshutokuzei_hyoujun: str
    fudousanshutokuzei_ritsu: str
    growth: str
    hojo_ritsu: str
    houjinzei_ritsu: str
    houjinjuminzei_kintou: str
    houjinjuminzei_ritsu_todouhuken: str
    houjinjuminzei_ritsu_shikuchoson: str
    ijikanri_unnei: str
    ijikanri_unnei_LCC: str
    ijikanri_unnei_org: str
    ijikanri_unnei_org_LCC: str
    ijikanri_unnei_1: str
    ijikanri_unnei_1_LCC: str
    ijikanri_unnei_1_org: str
    ijikanri_unnei_1_org_LCC: str
    ijikanri_unnei_2: str
    ijikanri_unnei_2_LCC: str
    ijikanri_unnei_2_org: str
    ijikanri_unnei_2_org_LCC: str
    ijikanri_unnei_3: str
    ijikanri_unnei_3_LCC: str
    ijikanri_unnei_3_org: str
    ijikanri_unnei_3_org_LCC: str
    ijikanri_unnei_years: int
    kappu_kinri_spread: str
    Kappu_kinri: str
    kijun_kinri: str
    kisai_jutou: str
    kisai_koufu: str
    kitai_bukka: str
    koteishisanzei_hyoujun: str
    koteishisanzei_ritsu: str
    lg_spread: str
    mgmt_type: str
    monitoring_costs_PSC: str
    monitoring_costs_LCC: str
    option_02: str
    pre_kyoukouka: bool
    proj_ctgry: str
    proj_type: str
    proj_years: int
    rakusatsu_ritsu: str
    reduc_shisetsu: str
    reduc_ijikanri_1: str
    reduc_ijikanri_2: str
    reduc_ijikanri_3: str
    riyouryoukin_shunyu: str
    shisetsu_seibi: str
    shisetsu_seibi_LCC: str
    shisetsu_seibi_org: str
    shisetsu_seibi_org_LCC: str
    shisetsu_seibi_paymentschedule_ikkatsu: str
    shisetsu_seibi_paymentschedule_kappu: str
    shoukan_kaishi_jiki: int
    SPC_keihi: str
    SPC_fee: str
    SPC_shihon: str
    SPC_yobihi: str
    SPC_hiyou_atsukai: int
    SPC_hiyou_total: str
    SPC_hiyou_nen: str
    SPC_keihi_LCC: str
    target_years: int
    tourokumenkyozei_hyoujun: str
    tourokumenkyozei_ritsu: str
    yosantanka_hiritsu_shisetsu: str
    yosantanka_hiritsu_ijikanri_1: str
    yosantanka_hiritsu_ijikanri_2: str
    yosantanka_hiritsu_ijikanri_3: str
    zei_total: str
